import { Inter, Noto_Serif, Poppins } from "next/font/google";
import ImgModelContextProvider from "@/src/_contextApi/ImgModelContextApi";
import "../globals.css";
import MainFooter from "@/src/_components/footer/MainFooter";
import ModelContextProvider from "@/src/_contextApi/ModelContextApi";
import AppContextProvider from "@/src/_contextApi/AppContext";
import MainAppNavbar from "@/src/_components/navbar/appnavbar/MainAppNavbar";
import { getSession } from "../lib/authentication";
import AuthContextProvider from "@/src/_contextApi/authContext";
import { featuredTagsListAction } from "../utils/tagActions";
import GoogleOneTap from "@/src/_components/googleAuth/GoogleOneTap";
import { GOOGLE_AUTH_CLIENT_ID } from "@/config";
import { GoogleOAuthProvider } from "@react-oauth/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const notoSerif = Noto_Serif({
  subsets: ["latin"],
  variable: "--font-noto-serif",
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  variable: "--font-poppins",
  display: "swap",
});
export const metadata = {
  title: "user Profile",
  description: "Generated by create next app",
};

export default async function TagPageLayout({ children }) {
  const userDetails = await getSession();
  const featuredTags = await featuredTagsListAction();
  return (
    <html
      lang="en"
      className={`${inter.variable} ${notoSerif.variable} ${poppins.variable}`}
    >
      <head />
      <body>
        <AuthContextProvider authData={userDetails}>
          <GoogleOAuthProvider clientId={GOOGLE_AUTH_CLIENT_ID}>
            <AppContextProvider>
              <ModelContextProvider>
                <ImgModelContextProvider>
                  <div>
                    <MainAppNavbar
                      authData={userDetails}
                      suggestList={featuredTags}
                    />
                    {!userDetails && <GoogleOneTap />}
                  </div>
                  <div className="layout_children_wrapper">{children}</div>
                  <div>
                    <MainFooter authData={userDetails} />
                  </div>
                </ImgModelContextProvider>
              </ModelContextProvider>
            </AppContextProvider>
          </GoogleOAuthProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
