import { Inter, Noto_Serif, Poppins } from "next/font/google";
import MainFooter from "@/src/_components/footer/MainFooter";
import MainAppNavbar from "@/src/_components/navbar/appnavbar/MainAppNavbar";
import UserdashboardUi from "@/src/_components/user_Dashboard/layout/UserdashboardUi";
import AppContextProvider from "@/src/_contextApi/AppContext";
import AuthContextProvider from "@/src/_contextApi/authContext";
import ImgModelContextProvider from "@/src/_contextApi/ImgModelContextApi";
import ModelContextProvider from "@/src/_contextApi/ModelContextApi";
import { getSession } from "../lib/authentication";
import InputModelContextProvider from "@/src/_contextApi/InputModelContextApi";
import { featuredTagsListAction } from "../utils/tagActions";
import DeleteModel from "@/src/_components/models/DeleteModel";
import WebStaticPageLayout from "@/src/_components/web_static/WebStaticPageLayout";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const notoSerif = Noto_Serif({
  subsets: ["latin"],
  variable: "--font-noto-serif",
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  variable: "--font-poppins",
  display: "swap",
});
export const metadata = {
  title: "user Profile",
  description: "Generated by create next app",
};

export default async function StaticLayout({ children }) {
  const userDetails = await getSession();
  const featuredTags = await featuredTagsListAction();
  return (
    <html
      lang="en"
      className={`${inter.variable} ${notoSerif.variable} ${poppins.variable}`}
    >
      <head />
      <body>
        <AuthContextProvider authData={userDetails}>
          <AppContextProvider>
            <InputModelContextProvider>
              <ModelContextProvider>
                <ImgModelContextProvider>
                  <DeleteModel />
                  <div>
                    <MainAppNavbar
                      authData={userDetails}
                      suggestList={featuredTags}
                    />
                  </div>
                  <div className="static_layout_children_wrapper">
                    <WebStaticPageLayout>{children}</WebStaticPageLayout>
                  </div>
                  <div>
                    <MainFooter authData={userDetails} />
                  </div>
                </ImgModelContextProvider>
              </ModelContextProvider>
            </InputModelContextProvider>
          </AppContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
