import "../globals.css";
import MainFooter from "@/src/_components/footer/MainFooter";
import MainAppNavbar from "@/src/_components/navbar/appnavbar/MainAppNavbar";
import UserdashboardUi from "@/src/_components/user_Dashboard/layout/UserdashboardUi";

export const metadata = {
  title: "user Profile",
  description: "Generated by create next app",
};

export default function UserpanelLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Noto+Serif:ital,wght@0,100..900;1,100..900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <div>
          <MainAppNavbar />
        </div>
        <div className="single_blog_layout_children_wrapper">
          <UserdashboardUi>{children}</UserdashboardUi>
        </div>
        <div>
          <MainFooter />
        </div>
      </body>
    </html>
  );
}
