import MainAppNavbar from "@/src/_components/navbar/appnavbar/MainAppNavbar";
import "../globals.css";
import HomePageLayout from "@/src/_components/home/layout/HomePageLayout";
import MainFooter from "@/src/_components/footer/MainFooter";
import AuthContextProvider from "@/src/_contextApi/authContext";
import ModelContextProvider from "@/src/_contextApi/ModelContextApi";
import AuthModel from "@/src/_components/models/AuthModel";
import ReportModel from "@/src/_components/models/ReportModel";
import { getSession } from "../lib/authentication";
import AppContextProvider from "@/src/_contextApi/AppContext";
import {
  featuredTagsListAction,
  verifiedTagsListAction,
} from "../utils/tagActions";
import TagContextProvider from "@/src/_contextApi/TagContextApi";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { GOOGLE_AUTH_CLIENT_ID } from "@/config";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const userDetails = await getSession();
  const featuredTags = await featuredTagsListAction();
  const verifiedTags = await verifiedTagsListAction();

  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Noto+Serif:ital,wght@0,100..900;1,100..900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <AuthContextProvider authData={userDetails}>
          <GoogleOAuthProvider clientId={GOOGLE_AUTH_CLIENT_ID}>
            <TagContextProvider verifiedTags={verifiedTags}>
              <AppContextProvider>
                <ModelContextProvider>
                  <AuthModel />
                  <ReportModel />
                  <div>
                    <MainAppNavbar authData={userDetails} />
                  </div>
                  <div className="layout_children_wrapper">
                    <HomePageLayout featuredTags={featuredTags}>
                      {children}
                    </HomePageLayout>
                  </div>
                  <div>
                    <MainFooter />
                  </div>
                </ModelContextProvider>
              </AppContextProvider>
            </TagContextProvider>
          </GoogleOAuthProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
