import { Inter, Noto_Serif, Poppins } from "next/font/google";
import MainAppNavbar from "@/src/_components/navbar/appnavbar/MainAppNavbar";

import "../globals.css";
import HomePageLayout from "@/src/_components/home/layout/HomePageLayout";
import MainFooter from "@/src/_components/footer/MainFooter";
import AuthContextProvider from "@/src/_contextApi/authContext";
import ModelContextProvider from "@/src/_contextApi/ModelContextApi";
import AuthModel from "@/src/_components/models/AuthModel";
import ReportModel from "@/src/_components/models/ReportModel";
import { getSession } from "../lib/authentication";
import AppContextProvider from "@/src/_contextApi/AppContext";
import {
  featuredTagsListAction,
  verifiedTagsListAction,
} from "../utils/tagActions";
import TagContextProvider from "@/src/_contextApi/TagContextApi";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { GOOGLE_AUTH_CLIENT_ID } from "@/config";
import MobileSearchModel from "@/src/_components/models/MobileSearchModel";
import GoogleOneTap from "@/src/_components/googleAuth/GoogleOneTap";
import MobileAppDrawer from "@/src/_components/app_Drawer/MobileAppDrawer";
import CustomePageLoading from "@/src/_components/loading/CustomePageLoading";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const notoSerif = Noto_Serif({
  subsets: ["latin"],
  variable: "--font-noto-serif",
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function homeLayout({ children }) {
  const userDetails = await getSession();
  const featuredTags = await featuredTagsListAction();
  const verifiedTags = await verifiedTagsListAction();

  return (
    <html
      lang="en"
      className={`${inter.variable} ${notoSerif.variable} ${poppins.variable}`}
    >
      <head>
        {/* Include serialized initial data for hydration */}
        <script
          id="initial-data"
          type="application/json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({ userDetails, featuredTags, verifiedTags }),
          }}
        />
      </head>
      <body>
        <AuthContextProvider authData={userDetails}>
          <GoogleOAuthProvider clientId={GOOGLE_AUTH_CLIENT_ID}>
            <TagContextProvider verifiedTags={verifiedTags}>
              <AppContextProvider>
                <ModelContextProvider>
                  <CustomePageLoading />
                  <MobileAppDrawer />
                  <AuthModel />
                  <ReportModel />
                  <MobileSearchModel suggestList={featuredTags} />
                  <div>
                    <MainAppNavbar
                      authData={userDetails}
                      suggestList={featuredTags}
                    />
                    {typeof userDetails !== "undefined" && !userDetails && (
                      <GoogleOneTap />
                    )}
                  </div>
                  <div className="layout_children_wrapper">
                    <HomePageLayout featuredTags={featuredTags}>
                      {children}
                    </HomePageLayout>
                  </div>
                  <div>
                    <MainFooter authData={userDetails} />
                  </div>
                </ModelContextProvider>
              </AppContextProvider>
            </TagContextProvider>
          </GoogleOAuthProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
