import AuthModel from "@/src/_components/models/AuthModel";
import "../../../globals.css";
import MainFooter from "@/src/_components/footer/MainFooter";
import MainAppNavbar from "@/src/_components/navbar/appnavbar/MainAppNavbar";
import UserProfileLayout from "@/src/_components/userProfile/layout/UserProfileLayout";
import AuthContextProvider from "@/src/_contextApi/authContext";
import ModelContextProvider from "@/src/_contextApi/ModelContextApi";
import ReportModel from "@/src/_components/models/ReportModel";
import { getSession } from "../../../lib/authentication";
import { API_BASE_URL, GOOGLE_AUTH_CLIENT_ID } from "@/config";
import { featuredTagsListAction } from "@/src/app/utils/tagActions";
import GoogleOneTap from "@/src/_components/googleAuth/GoogleOneTap";
import { GoogleOAuthProvider } from "@react-oauth/google";
import AppContextProvider from "@/src/_contextApi/AppContext";

export const metadata = {
  title: "user Profile",
  description: "Generated by create next app",
};

export default async function ProfileLayout({ children, params }) {
  const userDetails = await getSession();
  const featuredTags = await featuredTagsListAction();
  const slug = params?.slug;
  let userProfiledata;
  try {
    // Fetch the web stats using the auth token
    const res = await fetch(`${API_BASE_URL}/user/user-details/${slug}`, {
      method: "GET", // GET request to fetch the blog
      credentials: "include", // Include cookies in the request
      headers: {
        "Content-Type": "application/json", // Ensure this is set to JSON
      },
    });

    const initalData = await res.json();
    if (initalData.status === "success") {
      userProfiledata = initalData.result;
    }
  } catch (error) {
    console.error("Error fetching data:", error);
    userProfiledata = null;
  }

  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Noto+Serif:ital,wght@0,100..900;1,100..900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <AuthContextProvider authData={userDetails}>
          <GoogleOAuthProvider clientId={GOOGLE_AUTH_CLIENT_ID}>
            <AppContextProvider>
              <ModelContextProvider>
                <AuthModel />
                <ReportModel />
                <div>
                  <MainAppNavbar
                    authData={userDetails}
                    suggestList={featuredTags}
                  />
                  {!userDetails && <GoogleOneTap />}
                </div>
                <div className="single_blog_layout_children_wrapper">
                  <UserProfileLayout userProfile={userProfiledata}>
                    {children}
                  </UserProfileLayout>
                </div>
                <div>
                  <MainFooter authData={userDetails} />
                </div>
              </ModelContextProvider>
            </AppContextProvider>
          </GoogleOAuthProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
